# app.yaml
runtime: custom
env: flex

# This setting is important for CPU-intensive tasks like video conversion.
# It ensures that requests don't time out during the conversion process.
# For longer videos, you might need to increase this.
liveness_check:
  path: "/"
  check_interval_sec: 30
  timeout_sec: 10
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/"
  check_interval_sec: 30
  timeout_sec: 10
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 1800 # 30 minutes to allow for initial setup and cold starts

# Define environment variables. This is the secure way to handle secrets.
env_variables:
  FLASK_SECRET_KEY: '42882c490aabd51acd373b253f175ba05de35d845ee478736e3f634ffa0678df' # Replace with a real secret

# Define the resources for the instance. You can adjust these based on expected load.
# The 'cpu' and 'memory_gb' settings are crucial for video processing performance.
resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 20

# Network settings to allow all traffic
network: {}