# In app.yaml

runtime: custom
env: flex

# This connects App Engine to your VPC network
network:
  name: default

vpc_access_connector:
  name: "projects/video-to-gif-462512/locations/us-central1/connectors/vpc-connector"

liveness_check:
  path: "/"
  check_interval_sec: 30
  timeout_sec: 10
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/"
  check_interval_sec: 30
  timeout_sec: 10
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 1800

# Define environment variables with the CORRECT Redis IP
env_variables:
  FLASK_SECRET_KEY: "projects/video-to-gif-462512/secrets/flask-secret-key/versions/latest"
  # 👇 PASTE YOUR NEW REDIS IP ADDRESS HERE 👇
  CELERY_BROKER_URL: 'redis://10.124.0.3:6379/0' 
  CELERY_RESULT_BACKEND: 'redis://10.124.0.3:6379/0'

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 20